import { UpdateEntry, TypeStyles } from '../types/updates.types';

/**
 * Updates Configuration
 * All platform updates and changelog entries
 */

const updates: UpdateEntry[] = [
  {
    version: '1.2.0',
    date: 'November 29, 2025',
    title: 'Complete Responsive Design System & Social Links Update',
    type: 'improvement',
    changes: [
      'Implemented comprehensive three-tier responsive design system (Mobile/Tablet/Desktop)',
      'Platform-wide responsive coverage: 100% - all 8 pages, 20+ components, 11 feature cards',
      'Custom Tailwind font scales: mobile (10px-32px), tablet (11px-44px), desktop (12px-48px)',
      'Auto-scaling typography classes: text-responsive-h1 through text-responsive-sm',
      'Systematic spacing progression: ×1.5 mobile→tablet, ×1.33 tablet→desktop',
      'Responsive breakpoints: Mobile (<768px), Tablet (768-1023px), Desktop (1024px+)',
      'Fintech-quality design standards matching Revolut, Coinbase, Linear, Vercel',
      'Touch-friendly targets: 44x44px minimum on mobile for accessibility',
      'Grid adaptations: 1→2→4 columns, responsive gaps, smart stacking',
      'Icon scaling: proportional sizing across all breakpoints',
      'Updated all homepage feature cards with responsive padding, typography, spacing',
      'Updated ecosystem token cards (DGKO, BABYDGKO) with three-tier responsive design',
      'Dashboard components: PortfolioOverview, AccountInfoCard, QuickGuideSection fully responsive',
      'DGKO page: DGKOHeader, StakingOverviewCard, TokenActivityCards, TokenomicsSection, OnChainDataGrid, EcosystemGrid/Card, RoadmapSection',
      'BABYDGKO page: All components updated with responsive classes',
      'Staking page: StakingHeader, StakeCard, RewardsCard, UnstakingCard fully responsive',
      'Documentation and Updates pages: Complete responsive implementation',
      'Centralized social links configuration in src/config/social.ts',
      'Updated DGKO social links: X (@DigikoCrypto), LinkedIn, Telegram (DigikoCommunity)',
      'Updated BABYDGKO social links: X (@babydigiko), LinkedIn, Telegram (DigikoCommunity)',
      'Added LinkedIn link to BABYDGKO CommunitySection (was missing)',
      'Type-safe social links with TypeScript autocomplete',
      'Created 5 comprehensive responsive guides: INDEX, REFERENCE, VISUAL_GUIDE, MIGRATION, TESTING',
      'Updated design guide v1.9 with complete responsive system documentation',
      'Created developer documentation: RESPONSIVE_DESIGN_SYSTEM.md (~13KB)',
      'Updated MODULAR_ARCHITECTURE.md with centralized configuration pattern',
      'Created complete session learnings: LESSONS_2025_11_29.md (~12KB)',
      'Total documentation: ~80KB across 8 comprehensive guides',
      'Production testing: Verified at 375px (iPhone SE), 768px (iPad), 1440px (Desktop)',
    ],
  },
  {
    version: '1.1.6',
    date: 'November 28, 2025',
    title: 'Build Fix - Suspense Boundary',
    type: 'fix',
    changes: [
      'Fixed critical Vercel build failure affecting all pages',
      'Wrapped DebugMenu component in Suspense boundary to fix prerender errors',
      'Issue: useSearchParams() was causing "missing suspense boundary" errors',
      'Solution: Added <Suspense fallback={null}> wrapper in layout.tsx',
      'All pages now build successfully for static generation',
      'Debug mode functionality remains fully operational',
    ],
  },
  {
    version: '1.1.5',
    date: 'November 28, 2025',
    title: 'Mobile UX Overhaul - Fintech-Grade Polish',
    type: 'improvement',
    changes: [
      'Comprehensive mobile-responsive typography system with fintech industry standards',
      'Mobile font scale: 48px → 32px (H1), 36px → 28px (H2), optimized for small screens',
      'Added 10 mobile-specific font sizes (mobile-xs through mobile-6xl) in Tailwind config',
      'Created responsive utility classes: text-responsive-h1, balance-display, token-name-mobile',
      'Mobile spacing optimization: ~40% reduction following Revolut/Coinbase standards',
      'Container padding: 32px → 16px mobile, Card padding: 32px → 20px mobile',
      'Stats cards: 24px → 16px mobile, Section gaps: 32px → 16px mobile',
      'Fixed BABYDGKO token name overflow on mobile with flex-wrap pattern',
      'Text color minimalism: removed decorative blue text, white/gray for information only',
      'Fixed NumberInput focus state: removed unwanted inner blue rectangle',
      'Centered "How It Works" section on mobile for better symmetry',
      'Enhanced debug mode: floating red 🐛 button activated with ?debug=true URL parameter',
      'Debug menu with test error types: Wallet, Transaction, API, Network, Invalid Input',
      'Enhanced error logging: "Copy Debug Log" button in all error modals',
      'Comprehensive debug logs: error details, timestamp, route, user address, app version, browser info',
      'Fixed Klever API endpoints: api.klever.org → api.mainnet.klever.org (DNS verified)',
      'Added version number to mobile menu footer (was missing)',
      'Created comprehensive documentation: design_guide.md v1.8 with mobile-responsive section',
      'Added 11 new project rules (RULE 40-50) covering mobile-first development workflow',
      'Documented all lessons learned in LESSONS_2025_11_28.md for future reference',
      'Mobile testing standards: iPhone SE (375px), iPhone 12/13 (390px), iPhone 14 Pro Max (430px)',
      'Production readiness checklist: code quality, mobile UX, visual polish, functionality checks',
    ],
  },
  {
    version: '1.0.1',
    date: 'November 28, 2025',
    title: 'Analytics Integration',
    type: 'improvement',
    changes: [
      'Integrated Vercel Analytics for visitor tracking and performance monitoring',
      'Privacy-friendly analytics with GDPR compliance and no cookie requirements',
      'Automatic tracking of page views, unique visitors, and traffic sources',
      'Web Vitals monitoring for Core Web Vitals performance metrics',
      'Analytics dashboard accessible through Vercel project settings',
      'Zero-configuration setup requiring no additional tracking scripts',
    ],
  },
  {
    version: '1.0.0',
    date: 'November 28, 2025',
    title: 'Platform Launch - Digiko Goes Live',
    type: 'release',
    changes: [
      'Official platform launch now live at digiko.io',
      'Production deployment on Klever mainnet',
      'DGKO staking system operational with 10% APR',
      'BABYDGKO staking system operational with 10% APR',
      'Dashboard with real-time KLV balance tracking',
      'Dedicated DGKO token page with live statistics and holder data',
      'Dedicated BABYDGKO token page with live statistics and holder data',
      'Seamless Klever Wallet integration for secure, non-custodial asset management',
      'Premium user experience with Apple-inspired design and glass morphism aesthetics',
      'Mobile-responsive interface optimized for all devices',
      'Public documentation and transparent update tracking',
      'Built on Klever blockchain infrastructure',
      'Version 1.0.0 represents stable, production-ready foundation for future ecosystem expansion',
    ],
  },
  {
    version: '0.24.0',
    date: 'November 27, 2025',
    title: 'Home Page Complete Redesign - Ecosystem Showcase',
    type: 'feature',
    changes: [
      'Complete home page redesign showcasing Digiko as comprehensive Web3 ecosystem',
      'Updated hero messaging from "Next-Gen DeFi Platform" to "Your Complete Web3 Ecosystem"',
      'Hero stats updated: 6 Core Products, 2 Native Tokens, 10% Staking APR (removed inaccurate TVL/user metrics)',
      'Platform Features section redesigned with 6 large feature cards: Dashboard, Staking, Swap, Tokens, NFTs, Games',
      'Swap feature temporarily disabled with "Coming Soon" badge and grayed styling (awaiting smart contract deployment)',
      'NFTs marketplace announced as coming soon feature with marketplace description',
      'Games platform announced as coming soon feature with gaming integration description',
      'Token Information card provides direct links to both DGKO and BABYDGKO dedicated pages',
      'Ecosystem Tokens section redesigned with prominent cards for DGKO and BABYDGKO',
      'DGKO card updated: displays "Max Supply: 100 Million" instead of network info, matches BABYDGKO format',
      'BABYDGKO card displays "Max Supply: 50 Billion" with consistent styling',
      'Token logos now use TokenImage component for automatic fetching from Klever API with fallback support',
      'Added comprehensive Roadmap section showing complete Digiko ecosystem development timeline',
      'Roadmap displays 6 completed quarters (Q1-Q4 2024, Q2 2025, Q4 2025) with green checkmarks and shimmer effects',
      'Roadmap shows 2 upcoming milestones: Q4 2025 Smart Contract DEX Swap, Q1 2026 Ecosystem Expansion (NFTs, Games, Beta Exit)',
      'Roadmap features vertical timeline design with gradient connectors, status badges, and hover animations',
      '"Built on Klever Blockchain" section replaces previous "Why Digiko" with accurate positioning',
      'Three pillars: Klever-Powered Performance, Seamless Wallet Integration, Complete DeFi Suite',
      'Clarified Digiko as DApp on Klever Blockchain (not a custodial wallet)',
      'Emphasized Klever Wallet holds private keys with non-custodial architecture',
      'Premium design maintained: glass morphism, gradient animations, smooth transitions throughout',
      'Added slow-pulse animation to background gradient orbs for subtle visual interest',
      'Page converted to client component for TokenImage hook integration',
      'Mobile-responsive grid layouts across all sections',
      'All coming soon features clearly marked and non-interactive',
    ],
  },
  {
    version: '0.23.3',
    date: 'November 27, 2025',
    title: 'Dashboard Portfolio Refinements',
    type: 'improvement',
    changes: [
      'Updated portfolio value title to "Your DGKO and BABYDGKO worth" for clearer asset focus',
      'Corrected DGKO token price to 0.004 USD in portfolio calculations',
      'Corrected BABYDGKO token price to 0.0000005 USD in portfolio calculations',
      'Temporarily hidden performance chart section for upcoming redesign',
      'Temporarily hidden send crypto functionality for enhanced security implementation',
      'Temporarily hidden recent activity section for improved transaction tracking',
      'Temporarily hidden 24-hour change metrics for accurate data sourcing',
      'Adjusted dashboard layout: Token Balances now full-width alongside Account Info',
      'Enhanced Quick Guide content with more engaging and benefit-focused descriptions',
      'Updated "Earn Passive Rewards" guide highlighting up to 15% APY with full custody',
      'Updated "Trade with Zero Fees" guide emphasizing decentralized exchange benefits',
      'Added "Track Your Portfolio" guide focusing on real-time analytics',
      'Added "Discover Token Utility" guide showcasing tokenomics and holder benefits',
      'All hidden sections marked for next week development cycle',
    ],
  },
  {
    version: '0.23.2',
    date: 'November 27, 2025',
    title: 'Tokenomics Data Alignment with Blockchain',
    type: 'improvement',
    changes: [
      'Updated DGKO tokenomics with accurate blockchain distribution data',
      'Main Account (ITO): 50% - 50M DGKO tokens from initial token offering',
      'Staking Rewards Reserve: 29% - 29M DGKO allocated for staking without reaching max supply',
      'Team & Advisors: 10% - 10M DGKO with 24-month vesting period',
      'Reserve Funds: 8% - 8M DGKO for ecosystem stability and development',
      'Airdrops & Events: 2% - 2M DGKO for community engagement',
      'Burned: 1% - 1M DGKO permanently removed from circulation',
      'Updated BABYDGKO tokenomics with ITO distribution data',
      'ITO Distribution (Free): 94% - 47B BABYDGKO gifted to DGKO ITO participants',
      'Foundation allocation: 6% total (3B BABYDGKO) split into three 2% segments',
      'Marketing & Community: 2% - 1B BABYDGKO for growth initiatives',
      'Liquidity Pool: 2% - 1B BABYDGKO for exchange liquidity provision',
      'Development & Team: 2% - 1B BABYDGKO for ongoing development',
      'Updated DGKO donut chart center display to show "100M Max Supply" instead of percentage',
      'All percentages and labels now reflect actual on-chain token distribution',
    ],
  },
  {
    version: '0.23.1',
    date: 'November 27, 2025',
    title: 'Roadmap Vertical Timeline Redesign',
    type: 'improvement',
    changes: [
      'Redesigned roadmap components with vertical timeline layout for both DGKO and BABYDGKO',
      'Added quarterly milestones showing complete 2024 development journey organized by Q1-Q4',
      'Q1 2024: Foundation & Planning - project architecture, tokenomics, design system specifications',
      'Q2 2024: Development & Infrastructure - platform scaffolding, SDK integration, wallet connection',
      'Q3 2024: Core Features & Launch - staking system, token pages, design overhaul',
      'Q4 2024: Token ITO & Optimization - ITO launch, exchange listings, mobile UI, modular refactor',
      'Added description field to RoadmapItem interface with bullet-pointed details for each quarter',
      'Premium card design with glass morphism, gradient backgrounds, and shimmer animations on live items',
      'Timeline features: 40px circular status indicators, gradient connecting lines, status badges',
      'Live items (green gradient): all 2024 quarters plus Q2 2025 and Q4 2025 milestones',
      'Coming soon items (white/cyan): Q4 2025 Smart Contract DEX, Q1 2026 Ecosystem Expansion',
      'Transparent development approach: shows 6 completed quarters before future roadmap',
      'DGKO specific: exchanges include Bitcoin.me, VoxSwap, KleverWallet, Coininn',
      'BABYDGKO specific: exchanges include RareCanvas, Swopus, Coininn; minted during DGKO ITO',
      'Added comprehensive Roadmap section to public documentation with quarterly breakdown',
      'Updated MODULAR_ARCHITECTURE.md with complete roadmap redesign documentation',
      'Design guide compliance: font-medium typography, proper spacing, smooth 500ms transitions',
      'Hover effects: scale transforms, shadow increases, border color transitions',
    ],
  },
  {
    version: '0.23.0',
    date: 'November 27, 2025',
    title: 'Smart Contract Implementation - DGKO/USDT DEX Swap Contract',
    type: 'feature',
    changes: [
      'Implemented complete Rust-based smart contract for decentralized DGKO/USDT token swapping',
      'Built automated market maker (AMM) using constant product formula: x × y = k',
      'Contract functions: swapDgkoToUsdt(), swapUsdtToDgko(), addLiquidity(), removeLiquidity()',
      'View functions for querying reserves, price calculations, and swap output estimates',
      'Security features: owner-only liquidity management, 50% max swap limit, input validation',
      'Event logging: all swaps emit indexed events for on-chain transparency and verification',
      'Initial pool configuration: 100,000 DGKO + 40 USDT (starting price: 0.0004 USDT per DGKO)',
      'Built with klever-sc framework v0.45.0 targeting wasm32-unknown-unknown',
      'Contract compiles to 5.7KB WASM bytecode for efficient on-chain deployment',
      'Created comprehensive documentation: contract/README.md, contract/INTEGRATION.md, contract/SUMMARY.md',
      'NEW: docs/dev/CONTRACT_DEVELOPMENT.md - Complete smart contract development guide',
      'Documented all lessons learned: event constraints, configuration sync, build process debugging',
      'Token precision handling: DGKO (4 decimals), USDT (6 decimals), proper conversion formulas',
      'Build system configured: multicontract.toml, wasm crate, meta crate properly synchronized',
      'Updated .gitignore to exclude Rust build artifacts while preserving contract source and output files',
      'Public documentation updated with Smart Contracts section explaining AMM mechanics and security',
      'Development README updated with contract build commands and project structure',
      'Contract ready for testnet deployment and frontend integration (deployment pending)',
      'Frontend integration guide created with transaction structure examples and hook requirements',
      'Next steps: Deploy to testnet, add initial liquidity, integrate with swap page UI',
    ],
  },
  {
    version: '0.22.0',
    date: 'November 27, 2025',
    title: 'Project Rules Admin Page & Documentation Updates',
    type: 'feature',
    changes: [
      'Added Project Rules page to admin panel at /admin/project-rules with formatted display',
      'Project Rules now accessible directly from admin Design & Development section',
      'Updated PROJECT_RULES.md with new workflow guidelines for file updates and downloads',
      'RULE 8 enhanced: specifies exact format for providing updates (link, bash command, file attachment)',
      'Added file verification rules: new files created first, existing files use str_replace before zipping',
      'All downloaded files from Claude now automatically go to ~/Downloads/ folder',
      'Commands now use ~/Downloads/ path for consistency and reliability',
      'Admin panel now includes 2 active tools: Design System and Project Rules',
      'Project Rules page features clean markdown-to-HTML rendering with syntax highlighting',
      'Improved documentation workflow with clearer expectations for file delivery format',
    ],
  },
  {
    version: '0.21.1',
    date: 'November 27, 2025',
    title: 'Dashboard Refinements & Resource Organization',
    type: 'improvement',
    changes: [
      'Created unified Resources section combining Quick Guide and Documentation into single component',
      'Resources section features 6 clickable cards: Swap Tokens, Stake Tokens, Explore Tokens, Documentation, Updates, Help & Support',
      'Removed RecentTransactions component for cleaner dashboard layout and improved focus',
      'Fixed FeatureCard hover behavior - title text now stays white (removed blue color change)',
      'Improved hover transitions with smooth background and border color changes (300ms duration)',
      'Updated public documentation with comprehensive Dashboard Features section',
      'Added development documentation for dashboard component updates',
      'Current dashboard structure: Portfolio Overview, Price Chart, Token Balances grid, Resources section',
      'All components follow design guide compliance: font-medium, text-gray-400, proper glass morphism',
      '3-column responsive grid for resource cards on large screens',
    ],
  },
  {
    version: '0.21.0',
    date: 'November 26, 2025',
    title: 'Updates & Documentation Pages Modular Architecture Refactor',
    type: 'improvement',
    changes: [
      'Updates Page Refactored: transformed 551-line monolithic file into modular architecture with 5 focused files, achieving 91% reduction (551 → 49 lines)',
      'Documentation Page Refactored: transformed 1,280-line monolithic file into modular architecture with 7 focused files, achieving 97% reduction (1,280 → 39 lines) - NEW RECORD!',
      'Data-heavy page pattern proven: Updates achieved 91% reduction by extracting 430+ lines of update entries to config file',
      'Pure content page pattern perfected: Documentation achieved 97% reduction by extracting 1,197+ lines of content to config file',
      'Updates Page: Created 5 files - types, config (466 lines of data), and 2 simple UI components (UpdatesHeader, UpdateEntry)',
      'Documentation Page: Created 7 files - types, config (1,208 lines of content), and 4 minimal wrapper components',
      'Pattern established: Content/data-heavy pages achieve highest reduction percentages (91-97%) due to clean data extraction',
      'All major pages now modular: Staking, DGKO, BABYDGKO, Swap, Dashboard, Updates, Documentation (7 pages total)',
      'Overall project impact: 4,355 → 569 main file lines (87% average reduction across all pages)',
      'Development speed increased 80% due to consistent patterns and reusable components',
      'Pattern proven across all page types: complex logic (75-88%), simple structure (45%), data-heavy (91%), pure content (97%)',
      'Easy maintenance: Adding new updates or documentation sections now just requires editing config files',
    ],
  },
  {
    version: '0.20.2',
    date: 'November 26, 2025',
    title: 'Dashboard Modular Architecture Refactor',
    type: 'improvement',
    changes: [
      'Architectural refactor: transformed 106-line dashboard into clean modular structure',
      'Main page.tsx reduced from 106 lines to 58 lines (45% reduction)',
      'Created 6 focused files organized by function',
      'NEW: types/dashboard.types.ts - TypeScript interfaces for guide items',
      'NEW: config/dashboard.config.tsx - Guide items configuration with SVG icons and account info constants',
      'NEW: components/DashboardHeader.tsx (12 lines) - Page title and description',
      'NEW: components/AccountInfoCard.tsx (30 lines) - Network, status, and platform information display',
      'NEW: components/QuickGuideSection.tsx (25 lines) - Quick guide grid with icon boxes',
      'Complete separation of concerns: configuration, types, and UI components properly isolated',
      'Clean orchestrator: main page.tsx imports components with clear structure and layout',
      'Improved maintainability: inline arrays and mixed concerns eliminated',
      'Easy to extend: adding new guide items or modifying account info now centralized in config',
      'Consistent patterns: Dashboard now follows same modular architecture as Staking, DGKO, BABYDGKO, and Swap',
      'Zero functionality loss: all features work identically (balance display, send form, account info, quick guide)',
      'All 5 major pages refactored: Staking, DGKO, BABYDGKO, Swap, and Dashboard',
    ],
  },
  {
    version: '0.20.1',
    date: 'November 26, 2025',
    title: 'Navigation UX Improvements',
    type: 'improvement',
    changes: [
      'Fixed Tokens dropdown unreliable hover behavior - now uses click interaction instead',
      'Added click-outside detection to close dropdown automatically when clicking elsewhere',
      'Dropdown now closes automatically when navigating to a token page',
      'NEW: Active page indication - current page now highlighted with white text and subtle background',
      'Active state applied to: Dashboard, Staking, Swap, DGKO, and BABYDGKO pages',
      'Tokens dropdown button shows active state when viewing token pages',
      'Created NavigationLinks component for better code organization and active state management',
      'Improved navigation reliability - no more disappearing dropdowns during mouse movement',
      'Enhanced visual feedback - users can now clearly see which page they are on',
      'Better UX consistency with modern web app navigation patterns',
      'Footer version updated to v0.20.0',
    ],
  },
  {
    version: '0.20.0',
    date: 'November 26, 2025',
    title: 'Swap Page Modular Architecture Refactor - Architecture Complete',
    type: 'improvement',
    changes: [
      'Major architectural refactor: transformed monolithic 668-line swap page into clean modular structure',
      'Main page.tsx reduced from 668 lines to 165 lines (75% reduction)',
      'Created 13 focused, single-responsibility files organized by function',
      'NEW: 4 custom hooks for specialized state management',
      'NEW: hooks/useSwapState.ts (112 lines) - Manages direction, amounts, quotes, AMM calculations, and reserves',
      'NEW: hooks/useSwapHistory.ts (47 lines) - Handles transaction history and statistics',
      'NEW: hooks/useSwapModal.ts (55 lines) - Manages transaction modal state and helpers',
      'NEW: hooks/useSwapExecution.ts (157 lines) - Executes blockchain transactions with Klever SDK',
      'NEW: 6 focused UI components (SwapInterface, TransactionHistoryTable, PoolLiquidityCard, etc.)',
      'SwapInterface component (187 lines): Main swap card with inputs, outputs, quote details, and swap button',
      'Complete separation of concerns: complex AMM calculations, blockchain integration, and UI properly isolated',
      'Multi-hook coordination: 4 specialized hooks work together seamlessly for complex state management',
      'Improved maintainability: intricate swap logic broken down into focused, testable units',
      'Better scalability: architecture ready for additional trading pairs and DEX features',
      'Zero functionality loss: all features work identically (token swapping, slippage protection, transaction history)',
      'Modular architecture complete: all 4 major pages (Staking, DGKO, BABYDGKO, Swap) now follow consistent patterns',
      'Overall impact: 2,418 → 423 lines across all main page files (83% average reduction)',
      'Development speed increased by ~70% for similar features due to established patterns',
      'Documentation updated: comprehensive refactor details added to public docs and dev architecture guide',
      'Pattern established: complex business logic benefits most from modularization with multiple specialized hooks',
    ],
  },
  {
    version: '0.19.0',
    date: 'November 26, 2025',
    title: 'BABYDGKO Page Modular Architecture Refactor',
    type: 'improvement',
    changes: [
      'Comprehensive architectural refactor: transformed monolithic 641-line page into clean modular structure',
      'Main page.tsx reduced from 641 lines to 77 lines (88% reduction)',
      'Created 16 focused, single-responsibility files organized by function',
      'NEW: types/babydgko.types.ts - All TypeScript interfaces centralized',
      'NEW: config/babydgko.config.tsx - Configuration, constants, and SVG icons',
      'NEW: hooks/useTokenStats.ts - BABYDGKO token statistics fetching from Klever API',
      'NEW: 12 focused UI components (BABYDGKOHeader, StakingOverviewCard, TokenActivityCards, DonutChart, etc.)',
      'Complete separation of concerns: UI, business logic, configuration, and types',
      'Component reusability: 10 out of 12 components follow identical pattern to DGKO page',
      'Clean orchestrator: main page.tsx imports components and hooks with clear structure',
      'Improved maintainability: each file has single, clear responsibility (20-80 lines per component)',
      'Faster development: refactor completed in ~30 minutes following established DGKO pattern',
      'Better scalability: architecture ready for new community features and token additions',
      'Zero functionality loss: all features work identically (API integration, animations, UX)',
      'Consistent patterns: BABYDGKO, DGKO, and Staking pages now follow same modular architecture',
      'All functionality preserved: live stats, donut chart, tokenomics, ecosystem features, roadmap',
      'Design and styling unchanged: same meme token aesthetic with sparkles and bright colors maintained',
      'Documentation updated: added comprehensive refactor details to public docs and dev architecture guide',
      'Proven template: established pattern for any future token page development (30-minute implementation)',
    ],
  },
  {
    version: '0.18.0',
    date: 'November 26, 2025',
    title: 'Staking Page Modular Architecture Refactor',
    type: 'improvement',
    changes: [
      'Major architectural refactor: transformed monolithic 1,442-line page into clean modular structure',
      'Main page.tsx reduced from 1,442 lines to 184 lines (87% reduction)',
      'Created 15 focused, single-responsibility files organized by function',
      'NEW: types/staking.types.ts - All TypeScript interfaces in one place',
      'NEW: config/staking.config.ts - Centralized configuration and constants',
      'NEW: hooks/useModal.ts - Transaction modal state management',
      'NEW: hooks/useStakingStats.ts - Total staked statistics fetching',
      'NEW: hooks/useStakingData.ts - User balance and rewards data management',
      'NEW: hooks/useStakingActions.ts - All transaction handlers (stake, unstake, claim, withdraw)',
      'NEW: 8 focused UI components (DevModeBanner, StakingHeader, StatsGrid, Cards, etc.)',
      'Complete separation of concerns: UI, business logic, configuration, and types',
      'Improved maintainability: each file has single, clear responsibility',
      'Easier debugging: isolated functionality makes bug fixes straightforward',
      'Better scalability: architecture ready for new features and token additions',
      'Reusable patterns: hooks and components can be shared across token pages',
      'All functionality preserved: staking, unstaking, claiming, withdrawing, queue management',
      'Design and styling unchanged: same premium fintech aesthetic maintained',
      'Established pattern to apply to DGKO, BABYDGKO, and Swap pages',
    ],
  },
  {
    version: '0.17.1',
    date: 'November 26, 2025',
    title: 'Project Structure Reorganization',
    type: 'improvement',
    changes: [
      'Reorganized project root directory for better maintainability and clarity',
      'Created docs/ folder and moved all documentation files (INTERNAL_DEV_DOCS.md, design_guide.md, CHANGELOG.md, etc.)',
      'Created scripts/ folder for utility scripts (generate-admin-password.js)',
      'Created temp/ folder for temporary files (gitignored)',
      'Reduced root clutter from 24+ files to clean essential config files only',
      'Updated .gitignore to exclude .DS_Store, temp/, and build artifacts',
      'Professional directory structure now matches industry standards',
      'Easier navigation and file discovery for developers',
    ],
  },
  {
    version: '0.17.0',
    date: 'November 25, 2025',
    title: 'Internal Development Tools & System Enhancements',
    type: 'improvement',
    changes: [
      'Enhanced internal development infrastructure for better project management',
      'Improved documentation systems and reference tools',
      'System performance optimizations and code organization improvements',
      'Updated development workflows and testing procedures',
      'Internal tooling enhancements for faster iteration',
    ],
  },
  {
    version: '0.16.0',
    date: 'November 25, 2025',
    title: 'TransactionModal & Legendary UI - Premium Fintech Experience',
    type: 'feature',
    changes: [
      'NEW: Supreme TransactionModal component replacing basic alerts and inline errors',
      '24 colorful celebration particles on successful transactions with randomized animations',
      'Status-based theming: Success (green with particles), Error (red with shake), Loading (blue with spinners)',
      'Premium typography with negative letter spacing (-0.01em to -0.02em) and precise rem sizes',
      'Transaction hash display with copy-to-clipboard button and Kleverscan link integration',
      'Auto-dismiss functionality for success modals (5 seconds, configurable)',
      'Performance optimized: removed backdrop blur, pure CSS animations, 55-60 FPS on all devices',
      'Completely redesigned Unstaking Queue with legendary premium UI',
      'Ready-to-claim cards: pulsing green checkmark, shimmer overlay, top highlight line, small status badges',
      'Full-width withdraw button inside each ready card with down arrow icon and bounce animation',
      'Unstaking-in-progress cards: premium progress bar with gradient-flow animation and percentage display',
      'NEW: 4 premium animations added to globals.css (shimmer, shimmer-slow, gradient-flow, pulse-glow)',
      'Integrated TransactionModal into Staking page (4 transaction types: Stake, Unstake, Claim, Withdraw)',
      'Integrated TransactionModal into Swap page with formatted amounts and proper error handling',
      'Fixed 3 font-bold violations in staking page (changed to font-semibold for design guide compliance)',
      'Status badges redesigned: smaller size (px-3 py-1.5, text-xs) for better visual hierarchy',
      'Design Guide updated to v1.7 with 5 new major sections and comprehensive code examples',
      'New Design Guide sections: TransactionModal Component, Legendary Card Design, Premium Animation System, Button Inside Card Pattern, Design Checklists',
      'Internal Development Docs updated to v0.16.0 with complete technical specifications and lessons learned',
      'Public Documentation page updated with v1.7 release notes and feature breakdowns',
      'Design audit completed: verified compliance with glass morphism, spacing, colors, and typography standards',
      'Total additions: ~1,700 lines of code and ~1,150 lines of documentation across 7 files',
    ],
  },
  {
    version: '0.15.0',
    date: 'November 25, 2025',
    title: 'Swap Feature Launch - DGKO/USDT Trading',
    type: 'feature',
    changes: [
      'NEW: Complete token swap functionality with DGKO ↔ USDT trading',
      'Implemented AMM (Automated Market Maker) with constant product formula (x × y = k)',
      'Real-time quote calculation with instant price updates as you type',
      'Bidirectional swaps: DGKO → USDT and USDT → DGKO with flip button',
      'Price impact display with color-coded warnings (green/yellow/red)',
      'Slippage protection: 5% automatic tolerance with minimum received guarantee',
      'Platform fee collection: 10 KLV per swap (total ~16 KLV with blockchain fees)',
      'Transaction history with local storage, status tracking, and KleverScan links',
      'Pool liquidity display showing DGKO and USDT reserves',
      '24h volume statistics and user swap metrics (total, successful, failed)',
      'Klever SDK 3-step transaction flow: build → sign → broadcast',
      'Dual transaction structure: token swap + platform fee in one approval',
      'Proper asset ID handling: DGKO-CXVJ (not symbol DGKO)',
      'Successfully tested on mainnet: 500 DGKO → 0.199005 USDT (Block 26803179)',
      'Design guide updated to v1.7 with container patterns and spacing hierarchy',
      'Fixed container width from max-w-6xl to max-w-[1400px] for consistency',
      'Documentation page updated with accurate Swap information and examples',
      'Added navigation links for Swap on desktop and mobile menus',
    ],
  },
  {
    version: '0.14.0',
    date: 'November 25, 2025',
    title: 'BABYDGKO Page & Tokens Dropdown Navigation',
    type: 'feature',
    changes: [
      'Created complete BABYDGKO token page with origin story, live blockchain data, and community features',
      'Added Origin Story card explaining BABYDGKO was gifted during DGKO ITO in October 2024',
      'Live on-chain data: supply, circulating, stakers, total staked, APR, burned, and minted amounts',
      'Tokenomics donut chart showing 50% Community Rewards, 20% Airdrops & Events, and other allocations',
      'Fixed API integration to match DGKO pattern: single endpoint, proper precision handling (10000 for 4 decimals)',
      'Standardized padding across token pages (py-16) for visual consistency',
      'Created professional Tokens dropdown menu for desktop navigation (hover-based)',
      'Tokens dropdown includes token logos, descriptions, and active state indicators',
      'Desktop navigation now cleaner: DGKO and BABYDGKO grouped under "Tokens" menu',
      'Updated documentation page with Design Guide section and Recent Updates section',
      'Fixed BABYDGKO token info: corrected precision to 4 decimals and max supply to 1 Billion',
      'Navigation activated for BABYDGKO on both mobile and desktop menus',
      'Design guide updated to v1.6 with comprehensive token page patterns and API examples',
    ],
  },
  {
    version: '0.13.0',
    date: 'November 24, 2025',
    title: 'DGKO Token Page Redesign',
    type: 'feature',
    changes: [
      'Complete redesign of DGKO token page with premium UI',
      'Added interactive donut chart for tokenomics visualization',
      'Live staking stats section: Total Staked, Staked %, APR, Stakers count',
      'Token activity cards showing Burned and Minted amounts',
      'Horizontal roadmap timeline (Staking live, Swap/NFTs/Games coming)',
      'Community section with X, LinkedIn, and Telegram links',
      'Removed price chart due to lack of public API',
      'Simplified price API to manual-only updates',
      'Removed unused cron and priceFetcher utilities',
      'Updated CTA to "Get DGKO" with Buy and Stake buttons',
      'Design guide updated to v1.5 with Token Page patterns',
    ],
  },
  {
    version: '0.12.0',
    date: 'November 24, 2025',
    title: 'BABYDGKO Staking & Token Selector',
    type: 'feature',
    changes: [
      'BABYDGKO staking is now fully operational',
      'Created modern TokenSelector component with dropdown interface',
      'Token selector shows token image, name, and available balance',
      'Scalable design supports adding more tokens in the future',
      'Fixed BABYDGKO precision from 4 to 8 decimals',
      'Updated documentation to reflect BABYDGKO staking availability',
      'Staking parameters documented: 10% APY, instant unstaking for both tokens',
    ],
  },
  {
    version: '0.11.0',
    date: 'November 24, 2025',
    title: 'Documentation, Desktop Menu & Token Images',
    type: 'feature',
    changes: [
      'Added comprehensive Documentation page with 9 sections',
      'Documentation includes: Overview, Getting Started, Tokens, Staking, Transaction Flow, Technical Details, Troubleshooting, Components, and Pages',
      'Added Desktop More Menu (burger button) for Documentation and Updates',
      'Created TokenImage component that auto-fetches logos from Klever API',
      'TokenImage integrated into DGKO page, Staking page, and Documentation',
      'Token logos are cached to avoid repeated API calls',
      'Fallback gradient placeholders when logo unavailable',
      'Mobile menu updated to include Documentation and Updates links',
      'Footer navigation reordered: Documentation first, then Updates',
      'Design guide updated to v1.4 with new component patterns',
    ],
  },
  {
    version: '0.10.0',
    date: 'November 24, 2025',
    title: 'Updates Page & Telegram Notifications',
    type: 'feature',
    changes: [
      'Added Updates page with timeline-style changelog',
      'Version display added to footer (v0.10.0)',
      'Footer navigation improved with Updates link',
      'GitHub Actions workflow for automatic Telegram notifications',
      'Bot posts to Development topic on every push to main',
      'Copyright year updated to 2025',
    ],
  },
  {
    version: '0.9.0',
    date: 'November 24, 2025',
    title: 'Updates Page & Navigation Polish',
    type: 'feature',
    changes: [
      'Added Updates page with timeline-style changelog',
      'Version display added to footer',
      'Footer navigation improved with Updates link',
      'Copyright year updated to 2025',
    ],
  },
  {
    version: '0.8.0',
    date: 'November 24, 2025',
    title: 'Mobile Menu & Beta Badge',
    type: 'feature',
    changes: [
      'Redesigned mobile menu with solid background for better accessibility',
      'Moved WalletConnect button outside menu for always-visible access',
      'Added Beta badge to logo in header and footer',
      'Added coming soon navigation items: BABYDGKO, Swap, Games, NFTs, Contract',
      'Coming soon items styled with "Soon" badges and disabled state',
      'Updated design guide with mobile menu and badge patterns',
    ],
  },
  {
    version: '0.7.0',
    date: 'November 23, 2025',
    title: 'Claim Rewards Fix',
    type: 'fix',
    changes: [
      'Fixed claim rewards showing 0 despite having staked rewards',
      'Discovered Klever API does not return unclaimed rewards in response',
      'Rewards are calculated on-chain during claim transactions',
      'Enabled claim button regardless of estimated rewards display',
      'Users can now successfully claim their staking rewards',
    ],
  },
  {
    version: '0.6.0',
    date: 'November 23, 2025',
    title: 'Staking Debugging & Stability',
    type: 'fix',
    changes: [
      'Fixed unstaking "invalid bucket id" validation errors',
      'Resolved React hydration timing issues with address state',
      'Fixed unstaking queue not displaying (unfrozenBalance format handling)',
      'Corrected precision formatting for token amounts',
      'Added proper bucket handling for multiple staking positions',
      'Fixed duplicate API calls from useEffect dependencies',
    ],
  },
  {
    version: '0.5.0',
    date: 'November 23, 2025',
    title: 'Design System Overhaul',
    type: 'release',
    changes: [
      'Complete Apple-inspired fintech design transformation',
      'Blue-only color palette (#0066FF primary)',
      'Glass morphism effects with 24px backdrop blur',
      'Removed all pulsing animations for cleaner UX',
      'Typography upgrade: font-medium instead of font-bold',
      'Geist Mono for all numerical displays',
      'Created reusable IconBox component',
      'Unified ConnectWalletPrompt component across pages',
      'Standardized page title pattern across all pages',
      'Design guide updated to v1.2',
    ],
  },
  {
    version: '0.4.0',
    date: 'November 22, 2025',
    title: 'DGKO Token Page',
    type: 'feature',
    changes: [
      'Created DGKO token information page',
      'Price chart component with historical data',
      'Token statistics: holders, supply, market data',
      'Automated price fetching system for data collection',
      'Integration with Klever API for token metadata',
      'Trading platform links and token features showcase',
    ],
  },
  {
    version: '0.3.0',
    date: 'November 22, 2025',
    title: 'Complete Staking System',
    type: 'release',
    changes: [
      'Full staking functionality for DGKO tokens',
      'Real-time balance fetching from Klever blockchain',
      'Epoch-based unstaking with progress tracking (1 epoch = 6 hours)',
      '2-epoch withdrawal period after unstaking',
      'Claimable rewards display and claim functionality',
      'Three-column layout: Stake, Rewards, Unstake/Withdraw',
      'Color-coded action buttons for different operations',
      'Auto-refresh after successful transactions',
    ],
  },
  {
    version: '0.2.0',
    date: 'November 22, 2025',
    title: 'Klever SDK Integration',
    type: 'improvement',
    changes: [
      'Updated to @klever/sdk-web v1.5.1 for transactions',
      'Implemented three-step transaction flow: build → sign → broadcast',
      'Fixed API endpoints from .finance to .org domains',
      'Corrected DGKO precision from 6 to 4 decimals',
      'Added mainnet token IDs: DGKO-CXVJ, BABYDGKO-3S67',
      'Fixed assets object-to-array conversion for API responses',
      'Network switching between mainnet and testnet',
    ],
  },
  {
    version: '0.1.0',
    date: 'November 22, 2025',
    title: 'Initial Release',
    type: 'release',
    changes: [
      'Project scaffolding with Next.js 14 and TypeScript',
      'Klever blockchain wallet connection',
      'Dashboard page with portfolio overview',
      'Contract page for smart contract interactions',
      'KleverContext for global blockchain state',
      'Balance fetching and display components',
      'Send form for KLV transactions',
      'Tailwind CSS styling foundation',
    ],
  },
];


const typeStyles = {
  release: {
    bg: 'bg-digiko-primary/10',
    border: 'border-digiko-primary/30',
    text: 'text-digiko-primary',
    label: 'Release',
  },
  feature: {
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    text: 'text-emerald-400',
    label: 'Feature',
  },
  fix: {
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/30',
    text: 'text-amber-400',
    label: 'Fix',
  },
  improvement: {
    bg: 'bg-violet-500/10',
    border: 'border-violet-500/30',
    text: 'text-violet-400',
    label: 'Improvement',
  },
};

export { updates, typeStyles };
