// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Total number of exported functions:  12

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    digiko_swap
    (
        init => init
        upgrade => upgrade
        swapDgkoToKlv => swap_dgko_to_klv
        swapKlvToDgko => swap_klv_to_dgko
        addLiquidity => add_liquidity
        removeLiquidity => remove_liquidity
        setFeeCollector => set_fee_collector
        getDgkoReserve => get_dgko_reserve
        getKlvReserve => get_klv_reserve
        getPrice => get_price
        calculateOutput => calculate_output
        getOwner => owner
    )
}
